// ─── Bot Settings ─────────────────────────────────────────────────────────────
// Canonical runtime settings used by all active modules.

export const SETTINGS = {
  BOT_NAME: 'UltraMagnus',

  MODE: (process.env.MODE ?? 'paper') as 'paper' | 'live' | 'notify',
  PAPER_START_USDT: 1000,

  NOTIFICATIONS_ENABLED: (process.env.NOTIFICATIONS_ENABLED ?? (process.env.MODE === 'notify' ? 'true' : 'false')) === 'true',
  NOTIFY_PROVIDER: (process.env.NOTIFY_PROVIDER ?? 'telegram') as 'telegram' | 'webhook' | 'none',
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN ?? '',
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID ?? '',
  NOTIFY_WEBHOOK_URL: process.env.NOTIFY_WEBHOOK_URL ?? '',

  TAKER_FEE: 0.001,
  ACTIVE_STRATEGY: (process.env.ACTIVE_STRATEGY ?? 'bb-mean-reversion') as 'bb-mean-reversion' | 'vwap-ema-retrace' | 'rsi-stoch-swing',
  CANDLE_INTERVALS: ['1m', '5m'] as const,
  CANDLE_BUFFER_SIZE: 50,

  BB_PERIOD: 20,
  BB_STD_DEV: 2,
  RSI_PERIOD: 14,
  ATR_PERIOD: 14,
  RSI_ENTRY_MIN: 42,
  RSI_ENTRY_MAX: 72,
  RSI_EXIT_OVERBOUGHT: 78,
  VOLUME_MULTIPLIER: 1.05,

  MAX_POSITION_PERCENT: 0.25,
  MAX_CONCURRENT_POSITIONS: 3,
  TP_PERCENT: 0.006,
  SL_PERCENT: 0.0035,
  TRAILING_STOP_ATR_MULTIPLIER: 1.0,

  VOLATILITY_BASE_ATR_PERCENT: 0.004,
  TP_MIN_PERCENT: 0.004,
  TP_MAX_PERCENT: 0.012,
  SL_MIN_PERCENT: 0.0025,
  SL_MAX_PERCENT: 0.006,

  ENTRY_TIMEOUT_DEFAULT_MS: 15 * 60 * 1000,
  ENTRY_TIMEOUT_MIN_MS: 10 * 60 * 1000,
  ENTRY_TIMEOUT_MAX_MS: 20 * 60 * 1000,

  STRATEGY_TIMEFRAME: '15m',
  BUY_SIZE_USDT: 20,
  BB_ENTRY_MAX_DISTANCE_PERCENT: 0.003,
  BB_ENTRY_RSI_MAX: 35,
  BB_EXIT_RSI_MIN: 65,

  STRATEGY_DIRECTION_TIMEFRAME: '5m',
  STRATEGY_ENTRY_TIMEFRAME: '1m',
  EMA_FAST_PERIOD: 9,
  EMA_SLOW_PERIOD: 20,
  BREAKOUT_LOOKBACK_5M: 6,
  BREAKOUT_ARM_MS: 45 * 60 * 1000,
  EMA_RETRACE_TOLERANCE_PERCENT: 0.0015,
  STOP_BUFFER_PERCENT: 0.0005,
  DEFAULT_STOP_PERCENT: 0.0035,
  RISK_REWARD_RATIO: 2.0,
  CYCLE_COOLDOWN_MS: 5 * 60 * 1000,

  // ── RSI + StochRSI 4H Swing Strategy ────────────────────────────────────────
  SWING_TIMEFRAME: '4h' as const,
  SWING_HTF_TIMEFRAME: '1d' as const,
  SWING_RSI_PERIOD: 14,
  SWING_RSI_LONG_MIN: 30,
  SWING_RSI_LONG_MAX: 55,
  SWING_STOCHRSI_PERIOD: 14,
  SWING_STOCHRSI_K_PERIOD: 3,
  SWING_STOCHRSI_D_PERIOD: 3,
  SWING_STOCHRSI_OVERSOLD: 20,
  SWING_STOCHRSI_OVERBOUGHT: 80,
  SWING_EMA_FAST: 50,
  SWING_EMA_SLOW: 200,
  SWING_ATR_PERIOD: 14,
  SWING_ATR_STOP_MULTIPLIER: 1.5,
  SWING_MIN_CONFLUENCE: 3,
  SWING_RR_RATIO: 2.5,
  SWING_MACD_FAST: 12,
  SWING_MACD_SLOW: 26,
  SWING_MACD_SIGNAL: 9,
  SWING_VOLUME_MULTIPLIER: 1.2,
  SWING_COOLDOWN_MS: 4 * 60 * 60 * 1000,

  DAILY_PROFIT_LOCK_PERCENT: 0.04,
  DAILY_LOSS_CIRCUIT_BREAKER: -0.02,
  STRETCH_TARGET_PERCENT: 0.10,

  DASHBOARD_REFRESH_MS: 30_000,
  PRICE_TICKER_ENABLED: true,
  PRICE_TICKER_REFRESH_MS: 5_000,
  LOG_DIR: 'logs',
} as const;

export type Mode = typeof SETTINGS.MODE;
